### ISSUE TITLE
event not work..

### ISSUE THREAD

**Issue by zhangdarking** [splinetool/react-spline#86]
```
 <Spline
        scene="https://prod.spline.design/6Wq1Q7YGyM-iab9i/scene.splinecode"
        onLoad={(spline: Application) => {
          cube.current = spline.findObjectByName('Cube');
        }}
        onMouseDown={onMouseDown}
        onMouseHover={(e)=>{
          console.log(e)
        }}
      />
```
help !! mouseDown mouseHover event not trigger....

**Comment by zhangdarking** [comment]
Yeah... not only react, but also vanilla did not work.  Can I use low version spline?

**Comment by Rengaht** [comment]
Same problem here. Both emitEvent and onEvent listener are not working.

**Comment by zhangdarking** [comment]
Closed. the bug is is caused by spline.

**Comment by marcofugaro** [comment]
Thanks for your reports, we are working on it and will release a patch ASAP.

**Comment by marcofugaro** [comment]
Fixed in `@splinetool/runtime` version `0.9.126`

**Comment by edwindharris** [comment]
Awesome. Thank you!

**Comment by sebastiangraz** [comment]
I still experience this at `0.9.129`.
gif of the bug happening:
https://cdn.discordapp.com/attachments/936730866896502834/1033777594753097808/bug.gif

Notice how I'm able to click on the spline object while at the very top of the page. 
But once I scroll down, I can't click anymore. 
Scrolling back up and it works again. 
Looks as though the pointer boundary is being "scrolled away" out of view

**Comment by hannahcancode** [comment]
We can also replicate the issue - if you click on the spline without scrolling you can interact, if you scroll and then come back the interaction targets have moved with the scroll so they're no longer matching the images on the canvas.
